steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - dmv-elp-classification-cicd-test
    - --source=.
    - --trigger-http
    - --runtime=python38
    - --entry-point=hello_http
    - --allow-unauthenticated
    - --region=us-west1
    secretEnv: ['BUCKET_NAME']
availableSecrets:
  secretManager:
  - versionName: projects/elp-2022-352222/secrets/BUCKET_NAME/versions/1              
    env: BUCKET_NAME
