steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - dmv-elp-classification-cicd
    - --source=.
    - --trigger-http
    - --runtime=python38
    - --entry-point=hello_http
    - --allow-unauthenticated
